[[entries]]
id = "0240153b-1aaa-4801-b258-522c608bb936"
type = "improvement"
description = "Add None to the set of plain datatypes that can be de/serialized"
author = "@rhaps0dy"

[[entries]]
id = "693674ea-b2b2-4733-bce6-4d5bae59b164"
type = "fix"
description = "Fix #66: dataclasses inheriting from uninstantiated Generic did not get all their fields serialized"
author = "@rhaps0dy"
